app: epic-document-api  # Replace with your desired application name
githubRepo: https://github.com/bcgov/EPIC.epic-document.git  # Replace with your actual repo URL
githubContextDir: /epic-document-api
resources:
  limits:
    cpu: 1500m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 2Gi
