replicaCount: 1

image:
  repository: epic-document-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev"

resources:
  cpu:
    limit: 50m
    request: 25m
  memory:
    limit: 128Mi
    request: 64Mi

database:
  secret: epic-document-patroni
  service:
    name: epic-document-patroni
    port: 5432



service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

auth:
  jwt:
    alg: RS256
    aud: epic-document-web
    cacheEnabled: true
    issuer: https://test.loginproxy.gov.bc.ca/auth/realms/eao-epic
    cacheTimeout: "300"
    wellKnownConfig: https://test.loginproxy.gov.bc.ca/auth/realms/eao-epic/.well-known/openid-configuration
  keycloak:
    uri: https://test.loginproxy.gov.bc.ca
    realm:
    adminClientId:
    adminClientSecret:
python:
  pythonBuffered: 1
  connectTimeout: 60
