apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
data:
  JWT_OIDC_ALGORITHMS: {{ .Values.auth.jwt.alg }}
  JWT_OIDC_AUDIENCE: {{ .Values.auth.jwt.aud }}
  JWT_OIDC_CACHING_ENABLED: "{{ .Values.auth.jwt.cacheEnabled }}"
  JWT_OIDC_ISSUER: {{ .Values.auth.jwt.issuer }}
  JWT_OIDC_JWKS_CACHE_TIMEOUT: "{{ .Values.auth.jwt.cacheTimeout }}"
  JWT_OIDC_WELL_KNOWN_CONFIG: {{ .Values.auth.jwt.wellKnownConfig }}
  PYTHONBUFFERED: "{{ .Values.python.pythonBuffered }}"
  KEYCLOAK_BASE_URL: {{ .Values.auth.keycloak.uri }}
  KEYCLOAK_REALM_NAME: {{ .Values.auth.keycloak.realm }}
  CONNECT_TIMEOUT: "{{ .Values.python.connectTimeout }}"
  S3_ACCESS_KEY_ID: "{{ .Values.aws.key }}"
  S3_SECRET_ACCESS_KEY: "{{ .Values.aws.secret }}"
  S3_HOST: "{{ .Values.aws.host }}"
  S3_BUCKET: "{{ .Values.aws.bucket }}"
  S3_REGION: "{{ .Values.aws.region }}"
  S3_SERVICE: "{{ .Values.aws.service }}"
  CORS_ORIGIN: "{{ .Values.cors_origin }}"
